#!/usr/bin/env node
/**
 * Syncs the library version from packages/core/package.json to:
 * - stellar-appkit-docs/src/version.ts
 * - stellar-appkit-demos/src/lib/version.ts
 *
 * Run after bumping the library version:
 *   node scripts/sync-version.mjs
 *
 * This ensures the docs site and demos site headers always show the
 * correct library version they're documenting/using.
 */

import * as fs from 'node:fs';
import * as path from 'node:path';

const ROOT = path.resolve(import.meta.dirname, '..');

// Read the library version from packages/core/package.json
const corePkgPath = path.join(ROOT, 'packages/core/package.json');
const corePkg = JSON.parse(fs.readFileSync(corePkgPath, 'utf-8'));
const version = corePkg.version;

console.log(`Library version: ${version}`);

// --- Sync docs site ---
const docsVersionPath = path.join(ROOT, '..', 'stellar-appkit-docs', 'src', 'version.ts');
if (fs.existsSync(path.dirname(docsVersionPath))) {
  const docsContent = `/**
 * The library version this docs site documents.
 *
 * This is synced from packages/core/package.json in the library repo via
 * the sync-version.mjs script. When the library version changes, re-run:
 *   node scripts/sync-version.mjs
 *
 * DO NOT edit this file manually — it's auto-generated.
 */
export const LIBRARY_VERSION = '${version}';
`;
  fs.writeFileSync(docsVersionPath, docsContent, 'utf-8');
  console.log(`  ✓ Updated stellar-appkit-docs/src/version.ts → v${version}`);
} else {
  console.log('  ⚠ stellar-appkit-docs/src/ not found — skipping docs sync');
}

// --- Sync demos site ---
const demosVersionPath = path.join(ROOT, '..', 'stellar-appkit-demos', 'src', 'lib', 'version.ts');
if (fs.existsSync(path.dirname(demosVersionPath))) {
  const demosContent = `/**
 * The library version this demos site uses.
 *
 * This is synced from the library repo's packages/core/package.json via
 * the sync-version.mjs script. When the library version changes, re-run:
 *   node scripts/sync-version.mjs
 *
 * DO NOT edit this file manually — it's auto-generated.
 */
export const LIBRARY_VERSION = '${version}';
`;
  fs.writeFileSync(demosVersionPath, demosContent, 'utf-8');
  console.log(`  ✓ Updated stellar-appkit-demos/src/lib/version.ts → v${version}`);
} else {
  console.log('  ⚠ stellar-appkit-demos/src/lib/ not found — skipping demos sync');
}

console.log(`\nDone. Both sites now show v${version} in their headers.`);
